# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 20:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('customer_comment', models.CharField(max_length=500)),
                ('time_placed', models.DateTimeField(verbose_name='date order was placed')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_desc', models.CharField(max_length=200)),
                ('link_str', models.SlugField(blank=True, max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(through='pizza.Choice', to='pizza.Product'),
        ),
        migrations.AddField(
            model_name='choice',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza.Order'),
        ),
        migrations.AddField(
            model_name='choice',
            name='variety',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pizza.Product'),
        ),
    ]
