# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='variety',
            new_name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='price_big',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='price_small',
            field=models.IntegerField(default=0),
        ),
    ]
