# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 14:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='votes',
            new_name='amount',
        ),
    ]
