# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-15 22:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0002_auto_20171115_2338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price_small',
        ),
    ]
