# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0002_auto_20171106_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_desc',
            field=models.CharField(default='some description', max_length=200),
            preserve_default=False,
        ),
    ]
