# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-15 22:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0003_remove_product_price_small'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price_big',
            new_name='price',
        ),
    ]
