# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0003_question_question_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='link_str',
            field=models.SlugField(default='asdad', max_length=200),
            preserve_default=False,
        ),
    ]
