# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-15 23:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0004_auto_20171216_0021'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('OR', 'Ordered'), ('PR', 'Preparing'), ('SN', 'Sent'), ('RC', 'Received')], default='OR', max_length=2),
        ),
    ]
