# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-16 19:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0004_auto_20171216_0021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='order',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='pizza.Product'),
        ),
        migrations.AddField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('OR', 'Ordered'), ('PR', 'Preparing'), ('SN', 'Sent'), ('RC', 'Received')], default='OR', max_length=2),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
