# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 18:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0005_auto_20171114_2033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('time_placed', models.DateTimeField(verbose_name='date order was placed')),
            ],
        ),
        migrations.RenameField(
            model_name='choice',
            old_name='question',
            new_name='variety',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='choice_text',
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(through='pizza.Choice', to='pizza.Variety'),
        ),
        migrations.AddField(
            model_name='choice',
            name='order',
            field=models.ForeignKey(default='defOrder', on_delete=django.db.models.deletion.CASCADE, to='pizza.Order'),
            preserve_default=False,
        ),
    ]
