# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-17 23:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0006_order_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('CM', 'Composing'), ('OR', 'Ordered'), ('PR', 'Preparing'), ('SN', 'Sent'), ('RC', 'Received')], default='OR', max_length=2),
        ),
    ]
