# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-18 00:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0007_auto_20171218_0115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=500)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('CM', 'Composing'), ('OR', 'Ordered'), ('PR', 'Preparing'), ('SN', 'Sent'), ('RC', 'Received')], default='CM', max_length=2),
        ),
    ]
